# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "f5networks/demo"

  # Bugs that replace insecure public key doesn't seem to work reliably 
  # in certain versions (=~ 1.7.2 and up) so unfortunately leaving out
  # https://github.com/mitchellh/vagrant/issues/5186
  # https://github.com/mitchellh/vagrant/issues/5541
  # If you get repeated "default: Warning: Authentication failure. Retrying..."
  # Uncomment and set below value to false
  # config.ssh.insert_key=false

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  config.vm.network "public_network"
  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.network :forwarded_port, guest: 6379, host: 6379
  
  config.vm.synced_folder "../", "aws-deployments"

  # basic ssh and python environment setup
  config.vm.provision "shell", privileged: false, path: "../build/scripts/setup_env_vbox.sh"

end
