# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "f5networks/demo"

  # Bugs that replace insecure public key doesn't seem to work reliably 
  # in certain versions (=~ 1.7.2 and up) so unfortunately leaving out
  # https://github.com/mitchellh/vagrant/issues/5186
  # https://github.com/mitchellh/vagrant/issues/5541
  # If you get repeated "default: Warning: Authentication failure. Retrying..."
  # Uncomment and set below value to false
  # config.ssh.insert_key=false


  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  #config.vm.network "public_network"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 22, host: 2222

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "../", "/aws-deployments"

  # some bootstrapping to get python 2.7.9 installed
  #  config.vm.provision "shell", privileged: true, path: "install_python.sh"

  # basic ssh and python environment setup
  config.vm.provision "shell", privileged: false, path: "bootstrap.sh"

  config.vm.provision "file", source: ".f5aws", destination: "~/.f5aws"
  config.vm.provision "file", source: ".aws/credentials", destination: "~/.aws/credentials"

end
