---
# networking defaults
vpc_cidr_prefix: "172.16"

# defaults for all bigips deployed
# note: need m3.2xlarge to provision AVR
bigip_version: "11.6"
bigip_license_throughput: "25mbps"
bigip_license_model: "hourly"
bigip_license_package: "better"
bigip_instance_type: "m3.2xlarge"

# defaults for all gtms deployed
gtm_version: "11.6"
gtm_license_throughput: "25mbps"
gtm_license_model: "hourly"
gtm_license_package: "better"
gtm_instance_type: "m3.xlarge"


# defaults for deploying applications within docker containers
# default ami is Docker optimized in US-EAST-1
apphost_instance_type: "t2.micro"
containers_per_host: 2
apphosts_per_zone: 1

# defaults for deploying test client/jumbox
client_instance_type: "t2.micro"


# standalone big-ip in each availability zone, traffic directed
#  via gslb, dns
standalone_per_az:
  clustering: none
  bigips_per_zone: 1
  gtms_per_zone: 1

cluster_spanned_across_azs:
  clustering: cross-az
  bigips_per_zone: 1
  gtms_per_zone: 1

clustered_deviced_per_az:
  clustering: same-az
  bigips_per_zone: 2
  gtms_per_zone: 1

clustered_in_single_zone:
  clustering: same-az
  bigips_per_zone: 2
  gtms_per_zone: 1
