############################################################
# Dockerfile to build F5 Demo container images
# Based on Ubuntu
############################################################

# Set the base image to Ubuntu
FROM f5networks/demo

# File Author / Maintainer
MAINTAINER Alex Applebaum a.applebaum@f5.com

COPY .f5aws / 

COPY .aws / 
