############################################################
# Dockerfile to build F5 Demo container images
# Based on Ubuntu
############################################################

# Set the base image to Ubuntu
FROM smoothalg/f5demo

# File Author / Maintainer
MAINTAINER Alex Applebaum a.applebaum@f5.com

RUN mkdir .ssh

COPY .f5aws / 

COPY .aws / 
