# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "f5networks/demo"

  # Bug that replace key doesn't seem to work reliably in certain version so leaving out
  # https://github.com/mitchellh/vagrant/issues/5186
  config.ssh.insert_key=false

end
